### ISSUE TITLE
undefined, undefined when clicking on firefox

### ISSUE THREAD

**Issue by jedahan** [metmuseum-medialab/objectcrowdsourcer#1]
it creates a movable selection
![screen shot 2013-10-16 at 10 56 10 am](https://f.cloud.github.com/assets/32407/1343406/2d0bcd98-3673-11e3-9535-a0b4283a7f8f.png)

but does not read the x/y position
![screen shot 2013-10-16 at 10 56 22 am](https://f.cloud.github.com/assets/32407/1343405/2d07df80-3673-11e3-8559-d4b160add0c4.png)

**Comment by jedahan** [comment]
Feel free to assign to me

**Comment by donundeen** [comment]
in firefox on windows, it doesn't create the selection either.

**Comment by jedahan** [comment]
fixed in 155ba71933b8b1d0460094d9cc402264e3c5d39a
